name: Create config archive

on:
  push:
    branches:
    - develop
  workflow_dispatch:      # enable manual runs
  
jobs:
  create-archive:
    runs-on: ubuntu-latest

    steps:
    
    - name: Check out repo
      uses: actions/checkout@v3
      with:
        ref: develop     # hard-coded to allow for manual workflow runs
        # ref: ${{ github.ref_name }}
        token: ${{ secrets.VLSVC_PAT }}
        
    - name: Create archive file
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        directory: 'config/'
        filename: 'uberAgent.uAConfig'
        
    - name: Commit archive
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Updated config archive
        commit_user_name: vastlimits