name: Create config archive

on:
  push:
    branches:             # this YAML file needs to reside in all of the branches specified here
    - develop
  workflow_dispatch:      # enable manual runs
  
env:
  SourceDir:  config/
  TargetDir:  config-dist/
  TargetFile: uberAgent.uAConfig
  
jobs:
  create-archive:
    runs-on: ubuntu-latest

    steps:
    
    - name: Check out repo
      uses: actions/checkout@v3
      with:
        # ref: develop     # hard-coded to allow for manual workflow runs
        ref: ${{ github.ref_name }}
        token: ${{ secrets.VLSVC_PAT }}
        
    - name: Prepare target directory
      run: |
        # Print executed commands
        set -x
        
        mkdir -p $TargetDir
        rm -f $TargetDir$TargetFile
        
    - name: Create archive file
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: "zip"
        directory: "$TargetDir"
        path: "../$SourceDir"
        filename: "$TargetFile"
        
    - name: Commit archive
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Updated config archive
        commit_user_name: vastlimits